@Auth.API_HostAddress = http://localhost:5295

POST {{Auth.API_HostAddress}}/auth/register
Content-Type: application/json

{
  "userName": "daniel",
  "email": "daniel@example.com",
  "password": "Password123"
}

###

POST {{Auth.API_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "daniel@example.com",
  "password": "Password123"
}

###

GET {{Auth.API_HostAddress}}/auth/me
Accept: application/json
Authorization: Bearer {{accessToken}}

###
